import 'dotenv/config';
import mongoose from 'mongoose';
import Product from '../models/Product.js';

const products = [
  // ─── Organic ───────────────────────────────────────────────────────────────
  {
    name: 'Neem Gold Organic Fertilizer',
    description: 'Premium neem-based organic fertilizer that improves soil health, controls pests naturally, and enhances crop yield. Rich in nitrogen and other micro-nutrients.',
    category: 'Organic',
    cropTags: ['wheat', 'rice', 'vegetables', 'cotton', 'sugarcane'],
    price: 349,
    mrp: 450,
    unit: 'kg',
    stock: 150,
    manufacturer: 'Krishak Agro',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    npkRatio: { nitrogen: 4, phosphorus: 1, potassium: 2 },
    composition: 'Neem cake 80%, Neem oil 5%, Organic matter 15%',
    usage: 'Mix 2-3 kg per 100 sq ft of soil before planting. Water thoroughly.',
    benefits: ['Controls soil-borne pests', 'Improves soil microbiome', 'Safe for humans and animals', 'Slow-release nitrogen'],
    safetyPrecautions: ['Wear gloves during application', 'Store in cool dry place', 'Keep away from children'],
    isTrending: true,
    rating: 4.5,
    reviewCount: 312
  },
  {
    name: 'Vermicompost Premium (10 kg)',
    description: 'Nutrient-rich vermicompost made from earthworm castings. Improves soil structure, water retention, and provides complete nutrition for all crops.',
    category: 'Organic',
    cropTags: ['all crops', 'vegetables', 'fruits', 'flowers', 'herbs'],
    price: 299,
    mrp: 380,
    unit: 'kg',
    stock: 200,
    manufacturer: 'Green Earth Organics',
    imageUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=400',
    npkRatio: { nitrogen: 1.5, phosphorus: 1.2, potassium: 1.8 },
    composition: 'Vermicompost 100%, Earthworm castings',
    usage: 'Apply 200-500g per plant around the root zone. Water well after application.',
    benefits: ['Improves soil water retention', 'Increases microbial activity', 'pH neutral', 'Rich in micronutrients'],
    safetyPrecautions: ['No special precautions needed', 'Safe for organic farming'],
    isTrending: false,
    rating: 4.7,
    reviewCount: 489
  },
  {
    name: 'Bone Meal Organic NPK',
    description: 'Steamed bone meal providing slow-release phosphorus and calcium. Ideal for promoting root development and flowering in crops.',
    category: 'Organic',
    cropTags: ['flowers', 'vegetables', 'fruit trees', 'bulbs'],
    price: 425,
    mrp: 520,
    unit: 'kg',
    stock: 80,
    manufacturer: 'Organic Farm Solutions',
    imageUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400',
    npkRatio: { nitrogen: 3, phosphorus: 15, potassium: 0 },
    composition: 'Steamed bone meal 100%',
    usage: 'Mix 100-150g per plant into soil at planting time or as topdressing.',
    benefits: ['High phosphorus content', 'Promotes root growth', 'Long-lasting effect', 'Natural calcium source'],
    safetyPrecautions: ['Wear mask during application to avoid dust', 'Wash hands after use'],
    isTrending: false,
    rating: 4.2,
    reviewCount: 156
  },

  // ─── Chemical ──────────────────────────────────────────────────────────────
  {
    name: 'Urea N46 (Granular)',
    description: 'High-nitrogen urea fertilizer for rapid vegetative growth. Most widely used nitrogen fertilizer for all kharif and rabi crops in India.',
    category: 'Chemical',
    cropTags: ['wheat', 'rice', 'maize', 'sugarcane', 'cotton', 'oilseeds'],
    price: 299,
    mrp: 340,
    unit: 'bag',
    stock: 300,
    manufacturer: 'IFFCO',
    imageUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400',
    npkRatio: { nitrogen: 46, phosphorus: 0, potassium: 0 },
    composition: 'Urea 46% N',
    usage: 'Apply 25-50 kg per acre in 2-3 split doses. Incorporate into soil for best results.',
    benefits: ['Highest nitrogen concentration', 'Quick absorption by plants', 'Suitable for all soil types', 'Cost effective'],
    safetyPrecautions: ['Avoid contact with eyes and skin', 'Do not mix with superphosphate', 'Store in dry conditions'],
    isTrending: true,
    isFlashSale: true,
    rating: 4.4,
    reviewCount: 723
  },
  {
    name: 'DAP Diammonium Phosphate',
    description: 'Premium quality DAP fertilizer providing nitrogen and phosphorus essential for crop establishment and early growth. Recommended at sowing time.',
    category: 'Chemical',
    cropTags: ['wheat', 'paddy', 'maize', 'groundnut', 'soybean', 'pulses'],
    price: 1350,
    mrp: 1500,
    unit: 'bag',
    stock: 180,
    manufacturer: 'IFFCO',
    imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
    npkRatio: { nitrogen: 18, phosphorus: 46, potassium: 0 },
    composition: 'Diammonium Phosphate 18-46-0',
    usage: 'Apply 50 kg per acre at sowing. Best incorporated into soil 5-10 cm deep.',
    benefits: ['Promotes strong root development', 'Essential for seed germination', 'Improves crop stand', 'Phosphorus for energy transfer'],
    safetyPrecautions: ['Use gloves and mask during application', 'Avoid inhalation of dust', 'Keep away from water bodies'],
    isTrending: true,
    rating: 4.6,
    reviewCount: 564
  },
  {
    name: 'NPK 19-19-19 Water Soluble',
    description: 'Completely water-soluble NPK fertilizer for fertigation and foliar spray. Provides balanced nutrition for all growth stages.',
    category: 'Chemical',
    cropTags: ['vegetables', 'fruits', 'flowers', 'greenhouse crops', 'drip irrigation'],
    price: 890,
    mrp: 1050,
    unit: 'kg',
    stock: 120,
    manufacturer: 'Haifa Agro India',
    imageUrl: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400',
    npkRatio: { nitrogen: 19, phosphorus: 19, potassium: 19 },
    composition: 'Mono Ammonium Phosphate + Urea + Potassium Nitrate',
    usage: 'Dissolve 1-2 kg in 200L water for fertigation or 3-5g/L for foliar spray.',
    benefits: ['100% water soluble', 'No chlorides', 'Suitable for drip irrigation', 'Quick absorption'],
    safetyPrecautions: ['Wear protective gear', 'Do not mix with calcium fertilizers', 'Rinse equipment after use'],
    isTrending: false,
    isFlashSale: true,
    rating: 4.3,
    reviewCount: 298
  },

  // ─── Bio-Fertilizer ────────────────────────────────────────────────────────
  {
    name: 'Rhizobium Bio-Fertilizer',
    description: 'Contains Rhizobium bacteria that fix atmospheric nitrogen in legume root nodules. Reduces chemical fertilizer use by 25-30%.',
    category: 'Bio-Fertilizer',
    cropTags: ['soybean', 'groundnut', 'chickpea', 'lentil', 'pea', 'pulses'],
    price: 120,
    mrp: 150,
    unit: 'packet',
    stock: 250,
    manufacturer: 'Biofix Agri',
    imageUrl: 'https://images.unsplash.com/photo-1416920617757-9e7a05b8bb0a?w=400',
    composition: 'Rhizobium sp. (min 10^8 CFU/g) + carrier',
    usage: 'Mix 200g with 10 kg seeds before sowing. Dry in shade for 30 minutes before use.',
    benefits: ['Fixes atmospheric nitrogen', 'Reduces nitrogen fertilizer need', 'Improves soil biology', 'Eco-friendly'],
    safetyPrecautions: ['Do not mix with chemical pesticides or fungicides', 'Use fresh batch within 6 months', 'Store in cool place away from sunlight'],
    isTrending: false,
    rating: 4.1,
    reviewCount: 187
  },
  {
    name: 'Mycorrhiza Root Booster',
    description: 'Vesicular arbuscular mycorrhiza (VAM) that extends root network, enhances phosphorus uptake, and improves drought tolerance.',
    category: 'Bio-Fertilizer',
    cropTags: ['all crops', 'fruit trees', 'vegetables', 'ornamental plants'],
    price: 380,
    mrp: 480,
    unit: 'kg',
    stock: 90,
    manufacturer: 'Root Science Labs',
    imageUrl: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?w=400',
    composition: 'Glomus intraradices (min 1000 spores/g) + organic carrier',
    usage: 'Apply 5-10 kg per acre at transplanting or mix with seedling mix.',
    benefits: ['Increases nutrient uptake by 40%', 'Improves drought resistance', 'Enhances soil health', 'Reduces fertilizer requirement'],
    safetyPrecautions: ['Keep away from fungicides', 'Do not expose to direct sunlight', 'Use within best-before date'],
    isTrending: true,
    rating: 4.4,
    reviewCount: 203
  },
  {
    name: 'Azotobacter Bio-Nitrogen Fixer',
    description: 'Free-living nitrogen-fixing bacteria that enriches soil with atmospheric nitrogen for non-legume crops like wheat, rice, and vegetables.',
    category: 'Bio-Fertilizer',
    cropTags: ['wheat', 'rice', 'maize', 'vegetables', 'sugarcane'],
    price: 110,
    mrp: 140,
    unit: 'packet',
    stock: 300,
    manufacturer: 'Biofix Agri',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    composition: 'Azotobacter chroococcum (min 10^8 CFU/g)',
    usage: 'Seed treatment: Mix 200g with 10 kg seeds. Soil application: Mix 2 kg with compost per acre.',
    benefits: ['Fixes 20-30 kg N/ha per year', 'Produces growth hormones', 'Improves germination', 'Reduces urea requirement'],
    safetyPrecautions: ['Avoid contact with chemical fertilizers', 'Store below 30°C', 'Use fresh biofertilizer'],
    isTrending: false,
    rating: 4.0,
    reviewCount: 142
  },

  // ─── Pesticide ─────────────────────────────────────────────────────────────
  {
    name: 'Chlorpyrifos 20% EC',
    description: 'Broad-spectrum organophosphate insecticide for control of sucking pests, stem borers, and soil insects in major field crops.',
    category: 'Pesticide',
    cropTags: ['rice', 'cotton', 'maize', 'vegetables', 'groundnut'],
    price: 320,
    mrp: 400,
    unit: 'liter',
    stock: 100,
    manufacturer: 'Dhanuka Agritech',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400',
    composition: 'Chlorpyrifos 20% EC',
    usage: 'Dilute 2-3 ml per liter of water. Spray on foliage ensuring complete coverage.',
    benefits: ['Broad spectrum control', 'Effective against soil insects', 'Long residual activity', 'Controls multiple pests'],
    safetyPrecautions: ['Wear PPE (gloves, mask, goggles)', 'Do not spray near water bodies or on windy days', 'Pre-harvest interval: 15 days', 'Keep away from children and pets'],
    isTrending: false,
    rating: 4.2,
    reviewCount: 276
  },
  {
    name: 'Mancozeb 75% WP Fungicide',
    description: 'Multi-site contact fungicide for prevention and control of fungal diseases in vegetables, fruits, and field crops.',
    category: 'Pesticide',
    cropTags: ['tomato', 'potato', 'grape', 'wheat', 'onion', 'chilli'],
    price: 180,
    mrp: 220,
    unit: 'kg',
    stock: 130,
    manufacturer: 'UPL Limited',
    imageUrl: 'https://images.unsplash.com/photo-1624005740804-f84b38c5a9c4?w=400',
    composition: 'Mancozeb 75% WP',
    usage: 'Mix 2.5-3 g per liter of water. Apply as preventive spray at 10-14 day intervals.',
    benefits: ['Broad-spectrum fungal control', 'Preventive and curative action', 'Contains zinc and manganese micronutrients', 'Rain-fast formulation'],
    safetyPrecautions: ['Always wear protective mask', 'Avoid spraying during flowering', 'PHI 7 days for vegetables', 'Do not mix with alkaline products'],
    isTrending: true,
    rating: 4.3,
    reviewCount: 419
  },
  {
    name: 'Imidacloprid 17.8% SL Insecticide',
    description: 'Systemic neonicotinoid insecticide for control of sucking pests like aphids, whiteflies, thrips, and BPH in crops.',
    category: 'Pesticide',
    cropTags: ['cotton', 'rice', 'vegetables', 'sugarcane', 'tobacco'],
    price: 495,
    mrp: 580,
    unit: 'liter',
    stock: 75,
    manufacturer: 'Bayer CropScience',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400',
    composition: 'Imidacloprid 17.8% SL',
    usage: 'Dilute 0.5 ml per liter water. Soil drench: 0.75 ml per liter.',
    benefits: ['Systemic action throughout plant', 'Long lasting protection', 'Effective against resistant pests', 'Low dose requirement'],
    safetyPrecautions: ['Extremely toxic to bees — do not spray during flowering', 'Wear full PPE', 'PHI 21 days', 'Keep away from water sources'],
    isTrending: false,
    rating: 4.5,
    reviewCount: 348
  },

  // ─── Seeds ─────────────────────────────────────────────────────────────────
  {
    name: 'Hybrid Tomato Seeds (F1)',
    description: 'High-yielding hybrid tomato seeds, disease-resistant with excellent shelf life. Suitable for open field and protected cultivation.',
    category: 'Seeds',
    cropTags: ['tomato', 'vegetables', 'kharif', 'rabi'],
    price: 250,
    mrp: 320,
    unit: 'packet',
    stock: 200,
    manufacturer: 'Syngenta India',
    imageUrl: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400',
    composition: '10g hybrid F1 tomato seeds',
    usage: 'Sow in nursery beds, transplant after 25-30 days. Spacing: 60x45 cm.',
    benefits: ['High yield potential', 'TYLCV resistant', 'Excellent fruit quality', 'Long shelf life'],
    safetyPrecautions: ['Store in cool dry place', 'Use treated seeds within one season', 'Do not eat treated seeds'],
    isTrending: true,
    rating: 4.6,
    reviewCount: 512
  },
  {
    name: 'BT Cotton Hybrid Seeds',
    description: 'Bollgard II Bt cotton hybrid with dual gene protection against bollworm complex. High-yielding with good fiber quality.',
    category: 'Seeds',
    cropTags: ['cotton', 'kharif'],
    price: 730,
    mrp: 850,
    unit: 'packet',
    stock: 160,
    manufacturer: 'Mahyco Seeds',
    imageUrl: 'https://images.unsplash.com/photo-1503694978374-8a2fa686963a?w=400',
    composition: '450g (1 packet) Bollgard II hybrid cotton seeds',
    usage: 'Sow in June-July. Spacing 90x60 cm. 450g treats 1 acre.',
    benefits: ['Bollgard II dual gene technology', 'Excellent boll retention', 'High ginning outturn', 'Early maturity'],
    safetyPrecautions: ['Plant refuge area as per government guidelines', 'Store seeds in original packet', 'Follow IRM guidelines'],
    isTrending: true,
    rating: 4.3,
    reviewCount: 387
  },
  {
    name: 'Paddy IR-64 Certified Seeds',
    description: 'High-yielding semi-dwarf rice variety IR-64 suitable for irrigated lowland conditions. Medium maturity, good milling quality.',
    category: 'Seeds',
    cropTags: ['paddy', 'rice', 'kharif', 'irrigated'],
    price: 65,
    mrp: 80,
    unit: 'kg',
    stock: 500,
    manufacturer: 'National Seeds Corporation',
    imageUrl: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400',
    composition: 'IR-64 Certified Paddy Seeds',
    usage: 'Seed rate: 25-30 kg per acre for transplanting, 40-50 kg for direct seeding.',
    benefits: ['Semi-dwarf variety', 'Lodging resistant', 'Good grain quality', 'Suitable for mechanized harvesting'],
    safetyPrecautions: ['Treat with carbendazim before sowing', 'Use certified bags only', 'Store in cool dry conditions'],
    isTrending: false,
    rating: 4.2,
    reviewCount: 623
  },

  // ─── Equipment ─────────────────────────────────────────────────────────────
  {
    name: 'Knapsack Sprayer 16L Battery',
    description: 'Battery-operated knapsack sprayer with adjustable nozzle for uniform spray coverage. Lightweight, ergonomic design for comfort during extended use.',
    category: 'Equipment',
    cropTags: ['all crops', 'pesticide application', 'foliar spray'],
    price: 2800,
    mrp: 3500,
    unit: 'packet',
    stock: 45,
    manufacturer: 'Neptune Fairdeal Products',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    composition: '16L tank, 12V 8Ah battery, 4-nozzle boom, adjustable shoulder straps',
    usage: 'Charge fully before first use. Adjust pressure to 2-4 bar for optimal spray.',
    benefits: ['Battery operated — no hand pumping', 'Adjustable spray pattern', '16L large capacity', 'Chemical-resistant tank'],
    safetyPrecautions: ['Wear PPE when spraying chemicals', 'Clean sprayer thoroughly after each use', 'Check nozzles regularly for blockage', 'Store battery separately'],
    isTrending: true,
    rating: 4.4,
    reviewCount: 231
  },
  {
    name: 'Digital Soil pH & Moisture Meter',
    description: 'Accurate 3-in-1 soil tester measuring pH, moisture, and light intensity. Essential for precision farming and optimal crop management.',
    category: 'Equipment',
    cropTags: ['all crops', 'soil testing', 'precision farming'],
    price: 850,
    mrp: 1100,
    unit: 'packet',
    stock: 65,
    manufacturer: 'Agri Instruments India',
    imageUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400',
    composition: 'Digital display, stainless steel probes, pH 3.5-9 range, moisture 1-10 scale',
    usage: 'Insert probe 2-4 inches into moist soil. Wait 60 seconds for stable reading.',
    benefits: ['3-in-1 measurement', 'No batteries required', 'Instant readings', 'Durable stainless probes'],
    safetyPrecautions: ['Do not use in hard/rocky soils', 'Clean probes after each use', 'Store in dry conditions'],
    isTrending: false,
    isFlashSale: true,
    rating: 4.1,
    reviewCount: 178
  },
  {
    name: 'Hand Cultivator Set (5-Piece)',
    description: 'Premium stainless steel hand cultivator set for garden maintenance, loosening soil, weeding, and transplanting. Rust-resistant with ergonomic wooden handles.',
    category: 'Equipment',
    cropTags: ['garden', 'kitchen garden', 'nursery', 'vegetable garden'],
    price: 599,
    mrp: 799,
    unit: 'packet',
    stock: 85,
    manufacturer: 'Garden Pro Tools',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    composition: 'Trowel, transplanter, fork, weeder, cultivator — stainless steel with wooden handles',
    usage: 'Use appropriate tool for each task. Clean and oil after use to maintain quality.',
    benefits: ['5-piece complete set', 'Stainless steel blades', 'Ergonomic wooden handles', 'Rust and corrosion resistant'],
    safetyPrecautions: ['Keep tools sharp but handle with care', 'Store in dry place', 'Keep away from children'],
    isTrending: false,
    rating: 4.5,
    reviewCount: 342
  }
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    console.log('Cleared existing products');

    const inserted = await Product.insertMany(products);
    console.log(`Seeded ${inserted.length} products successfully`);

    await mongoose.disconnect();
    console.log('Done!');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error.message);
    process.exit(1);
  }
};

seed();
